# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0008_auto_20150512_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saler',
            options={'verbose_name': '\u5546\u5bb6', 'verbose_name_plural': '\u5546\u5bb6\u5217\u8868'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237\u5217\u8868'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='endTime',
            field=models.DateTimeField(verbose_name=b'\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='startTime',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='officialmsg',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='officialmsg',
            name='msg',
            field=models.CharField(max_length=400, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe4\xba\xba\xe5\x9c\xb0\xe5\x9d\x80'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='differSalerEvaluate',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\x95\x86\xe5\xae\xb6\xe6\x98\xaf\xe5\x90\xa6\xe8\xaf\x84\xe4\xbb\xb7\xe8\xbf\x87'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='isValidToSaler',
            field=models.BooleanField(default=True, verbose_name=b'\xe5\xaf\xb9\xe5\x95\x86\xe5\xae\xb6\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\xaf\xe8\xa7\x81'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='isValidToUser',
            field=models.BooleanField(default=True, verbose_name=b'\xe5\xaf\xb9\xe7\x94\xa8\xe6\x88\xb7\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\xaf\xe8\xa7\x81'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='memo',
            field=models.CharField(max_length=200, verbose_name=b'\xe5\xa4\x87\xe5\xbf\x98'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=20, verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe4\xba\xba\xe5\x90\x8d\xe5\xad\x97'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='payStyle',
            field=models.CharField(default=b'f', max_length=1, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe6\x96\xb9\xe5\xbc\x8f', choices=[('N', 'online'), ('F', 'offline')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='priceTotal',
            field=models.DecimalField(verbose_name=b'\xe6\x80\xbb\xe8\xae\xa1', max_digits=8, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='sendDay',
            field=models.CharField(max_length=8, verbose_name=b'\xe9\x85\x8d\xe9\x80\x81\xe6\x97\xa5\xe6\x9c\x9f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='sendStyle',
            field=models.CharField(default=b'S', max_length=1, verbose_name=b'\xe9\x85\x8d\xe9\x80\x81\xe6\x96\xb9\xe5\xbc\x8f', choices=[('S', b'SENDING'), ('G', b'GET')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='sendTimeEnd',
            field=models.CharField(max_length=4, verbose_name=b'\xe9\x85\x8d\xe9\x80\x81\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='sendTimeStart',
            field=models.CharField(max_length=4, verbose_name=b'\xe9\x85\x8d\xe9\x80\x81\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default=b'TBCT', max_length=4, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81', choices=[('TBCT', b'toBeCounted'), ('TBSN', b'toBeSend'), ('CCD', b'canceled'), ('TBCF', b'toBeConfirmed'), ('TBCM', b'toBeCommented'), ('FND', b'finished')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe4\xba\xba\xe7\x94\xb5\xe8\xaf\x9d'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='timeStamp',
            field=models.BigIntegerField(verbose_name=b'\xe6\x97\xb6\xe9\x97\xb4\xe6\x88\xb3'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='order',
            name='unreadBySaler',
            field=models.BooleanField(default=True, verbose_name=b'\xe5\x95\x86\xe5\xae\xb6\xe6\x98\xaf\xe5\x90\xa6\xe8\xaf\xbb\xe5\x8f\x96'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ordersku',
            name='everConfirmed',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe7\xa1\xae\xe8\xae\xa4\xe8\xbf\x87'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ordersku',
            name='everEvaluated',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\xaf\x84\xe4\xbb\xb7\xe8\xbf\x87'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ordersku',
            name='imgUrls',
            field=models.CharField(default=b'', max_length=300, verbose_name=b'\xe5\x9b\xbe\xe5\x83\x8furl'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ordersku',
            name='name',
            field=models.CharField(max_length=50, verbose_name=b'sku\xe5\x90\x8d\xe5\xad\x97'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ordersku',
            name='number',
            field=models.DecimalField(verbose_name=b'\xe6\x95\xb0\xe9\x87\x8f', max_digits=8, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ordersku',
            name='unit',
            field=models.CharField(default=b'w', max_length=1, verbose_name=b'sku\xe5\x8d\x95\xe4\xbd\x8d', choices=[('w', 'weight'), ('b', 'bag')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='ordersku',
            name='unitPrice',
            field=models.DecimalField(verbose_name=b'\xe5\x8d\x95\xe4\xbb\xb7', max_digits=8, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reportsaler',
            name='msg',
            field=models.CharField(max_length=300, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reportsaler',
            name='reason',
            field=models.CharField(max_length=2, verbose_name=b'\xe7\x90\x86\xe7\x94\xb1', choices=[('CF', b'click farming'), ('PH', b'price too high')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='msg',
            field=models.CharField(max_length=300, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='reason',
            field=models.CharField(max_length=2, verbose_name=b'\xe7\x90\x86\xe7\x94\xb1', choices=[('WA', b'wrong address'), ('BO', b'badly order'), ('OT', b'others')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='accountLeft',
            field=models.DecimalField(default=0, verbose_name=b'\xe4\xbd\x99\xe9\xa2\x9d', max_digits=7, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='addressDetail',
            field=models.CharField(max_length=100, verbose_name=b'\xe8\xaf\xa6\xe7\xbb\x86\xe4\xbf\xa1\xe6\x81\xaf'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='averageAttitudeLevel',
            field=models.DecimalField(default=5, verbose_name=b'\xe6\x80\x81\xe5\xba\xa6\xe8\xaf\x84\xe4\xbb\xb7', max_digits=3, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='averageQualityLevel',
            field=models.DecimalField(default=5, verbose_name=b'\xe8\xb4\xa8\xe9\x87\x8f\xe8\xaf\x84\xe4\xbb\xb7', max_digits=3, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='averageSpeedLevel',
            field=models.DecimalField(default=5, verbose_name=b'\xe9\x80\x9f\xe5\xba\xa6\xe8\xaf\x84\xe4\xbb\xb7', max_digits=3, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='basePrice',
            field=models.PositiveSmallIntegerField(default=10, verbose_name=b'\xe8\xb5\xb7\xe9\x80\x81\xe4\xbb\xb7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='city',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x9f\x8e\xe5\xb8\x82'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='description',
            field=models.CharField(max_length=200, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='district',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x9c\xb0\xe5\x8c\xba'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='everVerified2Saler',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\xae\xa4\xe8\xaf\x81\xe8\xbf\x87'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='headImage',
            field=models.CharField(max_length=100, verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='isServiceOn',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x9c\xa8\xe7\xba\xbf\xe6\x9c\x8d\xe5\x8a\xa1'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='isVerified',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe8\xa2\xab\xe8\xae\xa4\xe8\xaf\x81\xe8\xbf\x87'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='lastLoginTime',
            field=models.CharField(default=b'0', max_length=13, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe7\x99\xbb\xe5\xbd\x95\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=b'\xe7\xba\xa7\xe5\x88\xab'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='moneyEarned',
            field=models.DecimalField(default=0, verbose_name=b'\xe7\xb4\xaf\xe8\xae\xa1\xe6\x94\xb6\xe5\x85\xa5', max_digits=7, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='name',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='orderNumber',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xe7\xb4\xaf\xe8\xae\xa1\xe8\xae\xa2\xe5\x8d\x95'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='province',
            field=models.CharField(max_length=20, verbose_name=b'\xe7\x9c\x81\xe4\xbb\xbd'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='salerType',
            field=models.CharField(max_length=1, verbose_name=b'\xe5\x95\x86\xe5\xae\xb6\xe7\xb1\xbb\xe5\x9e\x8b', choices=[('f', 'fruit'), ('v', 'vegetable'), ('o', 'others')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='serviceTime',
            field=models.CharField(max_length=60, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe6\x97\xb6\xe9\x97\xb4'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='sex',
            field=models.CharField(default=b'u', max_length=1, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab', choices=[('f', 'female'), ('m', 'male'), ('u', 'unKnown')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='skuNumber',
            field=models.PositiveIntegerField(default=0, verbose_name=b'sku\xe6\x95\xb0\xe9\x87\x8f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='telephone',
            field=models.CharField(unique=True, max_length=11, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='verifyBackImage',
            field=models.CharField(max_length=100, verbose_name=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe5\x8f\x8d\xe9\x9d\xa2\xe7\x85\xa7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='saler',
            name='verifyFrontImage',
            field=models.CharField(max_length=100, verbose_name=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe6\xad\xa3\xe9\x9d\xa2\xe7\x85\xa7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='salerevaluate',
            name='attitudeLevel',
            field=models.PositiveSmallIntegerField(verbose_name=b'\xe6\x80\x81\xe5\xba\xa6\xe8\xaf\x84\xe4\xbb\xb7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='salerevaluate',
            name='comment',
            field=models.CharField(max_length=400, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='salerevaluate',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='salerevaluate',
            name='imgUrls',
            field=models.CharField(max_length=300, verbose_name=b'\xe5\x9b\xbe\xe5\x83\x8furl'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='salerevaluate',
            name='qualityLevel',
            field=models.PositiveSmallIntegerField(verbose_name=b'\xe8\xb4\xa8\xe9\x87\x8f\xe8\xaf\x84\xe4\xbb\xb7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='salerevaluate',
            name='speedLevel',
            field=models.PositiveSmallIntegerField(verbose_name=b'\xe9\x80\x9f\xe5\xba\xa6\xe8\xaf\x84\xe4\xbb\xb7'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='averageQualityLevel',
            field=models.DecimalField(default=0, verbose_name=b'\xe8\xb4\xa8\xe9\x87\x8f\xe7\xba\xa7\xe5\x88\xab', max_digits=3, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='description',
            field=models.CharField(max_length=200, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='img',
            field=models.CharField(max_length=500, verbose_name=b'\xe5\x9b\xbe\xe5\x83\x8f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='isOnSale',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe4\xbf\x83\xe9\x94\x80'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='isOnStock',
            field=models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe4\xb8\x8a\xe6\x9e\xb6'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=50, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='oriPrice',
            field=models.DecimalField(verbose_name=b'\xe4\xbb\xb7\xe6\xa0\xbc', max_digits=8, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='salePrice',
            field=models.DecimalField(verbose_name=b'\xe4\xbf\x83\xe9\x94\x80\xe4\xbb\xb7\xe6\xa0\xbc', max_digits=8, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='soldRecently',
            field=models.DecimalField(default=0, verbose_name=b'\xe6\x9c\x80\xe8\xbf\x91\xe5\x8d\x96\xe5\x87\xba', max_digits=8, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='soldTotally',
            field=models.DecimalField(default=0, verbose_name=b'\xe6\x80\xbb\xe5\x85\xb1\xe5\x8d\x96\xe5\x87\xba', max_digits=8, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xe5\xba\x93\xe5\xad\x98'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sku',
            name='unit',
            field=models.CharField(default=b'w', max_length=1, verbose_name=b'\xe5\x8d\x95\xe4\xbd\x8d', choices=[('w', 'weight'), ('b', 'bag')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='user',
            name='accountBalance',
            field=models.DecimalField(default=0, verbose_name=b'\xe4\xbd\x99\xe9\xa2\x9d', max_digits=7, decimal_places=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='user',
            name='defaultAddressId',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xe9\xbb\x98\xe8\xae\xa4\xe5\x9c\xb0\xe5\x9d\x80id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='user',
            name='headImage',
            field=models.CharField(max_length=50, verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLoginTime',
            field=models.CharField(max_length=13, null=True, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe7\x99\xbb\xe5\xbd\x95\xe6\x97\xb6\xe9\x97\xb4', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=b'\xe7\xba\xa7\xe5\x88\xab'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='user',
            name='nickName',
            field=models.CharField(max_length=50, verbose_name=b'\xe6\x98\xb5\xe7\xa7\xb0'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=b'\xe7\xa7\xaf\xe5\x88\x86'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(unique=True, max_length=11, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x9f\x8e\xe5\xb8\x82'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='detail',
            field=models.CharField(max_length=100, verbose_name=b'\xe8\xaf\xa6\xe7\xbb\x86\xe4\xbf\xa1\xe6\x81\xaf'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='district',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x9c\xb0\xe5\x8c\xba'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='name',
            field=models.CharField(max_length=20, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='province',
            field=models.CharField(max_length=20, verbose_name=b'\xe7\x9c\x81\xe4\xbb\xbd'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='tag',
            field=models.CharField(default=b'N', max_length=1, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe', choices=[('H', 'home'), ('S', 'school'), ('C', 'company'), ('N', 'none')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d'),
            preserve_default=True,
        ),
    ]
